version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: file:/data/sqlite.db
      PORT: "8080"
      NODE_ENV: "production"
    ports:
      - "8080:8080"
    volumes:
      - .:/myapp
